# Generated by Django 2.2.5 on 2019-09-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('Artista', models.CharField(max_length=50, verbose_name='Artista')),
                ('genero_musical', models.CharField(max_length=255, unique=True, verbose_name='Genero musical')),
                ('link', models.CharField(max_length=255, verbose_name='link da musica')),
            ],
        ),
    ]
