# Generated by Django 2.2.5 on 2019-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caieirasfy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da musica'),
        ),
    ]
