# Generated by Django 2.2.5 on 2019-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caieirasfy', '0002_auto_20190906_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da musica '),
        ),
    ]
