# Generated by Django 2.2.5 on 2019-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caieirasfy', '0003_auto_20190913_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='tempo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
